# Generated by Django 2.2.16 on 2020-10-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('name', models.CharField(max_length=80,primary_key=True)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=60)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
            ],
        ),

    ]
