# Generated by Django 2.2.16 on 2020-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0002_auto_20201023_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='id',
        ),
        migrations.AlterField(
            model_name='insumos',
            name='name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
