# Generated by Django 2.2.16 on 2020-10-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0004_sliderhindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('ident', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
